In [1]:
# Import modules

import tensorflow as tf

In [2]:
# Print version

tf.__version__

'2.1.0'

In [5]:
# Declare 3x3 tensors with random values

x = tf.random.normal(shape=(3, 3))
y = tf.random.normal(shape=(3, 3))

In [8]:
# Eager execution is letting us skip all the graph session

print("Tensor x is:", x)
print("Tensor y is:", y)

Tensor x is: tf.Tensor(
[[ 1.1656096   0.05655556 -2.112155  ]
 [-1.0343062   0.13542165  0.50263804]
 [ 1.0403721  -0.67204964  0.7652352 ]], shape=(3, 3), dtype=float32)
Tensor y is: tf.Tensor(
[[-0.4649665  -2.3577511  -1.4340464 ]
 [-0.54458827  1.1283857   2.03892   ]
 [-0.33475885  0.20941909  0.86807925]], shape=(3, 3), dtype=float32)


In [9]:
print("The sum of tensors is:", x + y)

The sum of tensors is: tf.Tensor(
[[ 0.70064306 -2.3011956  -3.5462012 ]
 [-1.5788944   1.2638073   2.541558  ]
 [ 0.70561326 -0.46263057  1.6333144 ]], shape=(3, 3), dtype=float32)
